Repository temporalio/temporal-learning, pull requests merged in 2024-12, with the labels that each got.

#338 EDU-3623: Add missing argument to `go mod init`
  docs/getting_started/go/dev_environment/index.md
Labels: community-contribution, tracked-internally

#318 add dprint and remove unmaintained docsync script
  README.md
  docs/tutorials/go/background-check/durable-execution.mdx
  docs/tutorials/go/background-check/index.mdx
  docs/tutorials/go/background-check/introduction.mdx
  docs/tutorials/go/background-check/project-setup.mdx
  docs/tutorials/java/background-check/durable-execution.mdx
  docs/tutorials/java/background-check/introduction.mdx
  docs/tutorials/java/background-check/project-setup.mdx
  docs/tutorials/python/background-check/durable-execution.mdx
  docs/tutorials/python/background-check/introduction.mdx
  docs/tutorials/python/background-check/project-setup.mdx
  docs/tutorials/typescript/background-check/durable-execution.mdx
  docs/tutorials/typescript/background-check/introduction.mdx
  docs/tutorials/typescript/background-check/project-setup.mdx
  docs/tutorials/typescript/work-queue-slack-app/build/index.mdx
  docs/tutorials/typescript/work-queue-slack-app/deploy/index.mdx
  docsync.sh
  dprint.json
  package.json
  yarn.lock
Labels: infrastructure

#342 rewrite go ecommerce tutorial
  docs/tutorials/go/build-an-ecommerce-app/images/frontend.png
  docs/tutorials/go/build-an-ecommerce-app/index.md
  docs/tutorials/go/build-an-ecommerce-app/part1.md
  docs/tutorials/go/build-an-ecommerce-app/part2.md
  docs/tutorials/go/build-an-ecommerce-app/part3.md
  docs/tutorials/go/build-an-ecommerce-app/part4.md
Labels: revision
